; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26431.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\EmreAsus\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
